### ISSUE TITLE
packagist outdated

### ISSUE THREAD

**Issue by koehnlein** [smichaelsen/no-insecure-typo3-extensions#1]
The latest release on https://packagist.org/packages/smichaelsen/no-insecure-typo3-extensions ist outdated and from last december. So `composer update smichaelsen/no-insecure-typo3-extensions --dry-run` only finds latest security conflicts when I add the repository manually to my `composer.json`

```json
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/smichaelsen/no-insecure-typo3-extensions.git"
    }
  ]
```

**Comment by smichaelsen** [comment]
Thanks for the report. Packagist stopped updating because one of the conflicting packages had an invalid package name. That is fixed now. The updater validates all package names.
